name: Gitleaks Scan

on:
  push:
    branches:
      - main

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Gitleaks
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/download/v7.3.0/gitleaks-linux-amd64
        mv gitleaks-linux-amd64 gitleaks
        chmod +x gitleaks

    - name: Run Gitleaks
      run: |
        ./gitleaks detect -v --report-format json --redact --no-git --source file_with_secret.py --report-path report.json
